version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: naksh1414-backend
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - PORT=5000
      - MONGO_URI=mongodb+srv://ecellwebtechnical:ecelltech1234@endeavour.xh40p.mongodb.net/?retryWrites=true&w=majority&appName=Endeavour
      - JWT_SECRET=your-secret-key
      - EMAIL_HOST=smtp.gmail.com
      - EMAIL_PORT=587
      - EMAIL_SECURE=false
      - EMAIL_USER=sakshambro730@gmail.com
      - EMAIL_PASS=vszc qypk kmey vflz
      - EMAIL_FROM="Your App <noreply@example.com>"
    volumes:
      - .:/app
      - /app/node_modules
    restart: unless-stopped

volumes:
  mongo_data:
